package com.qianfeng.android.myapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECTION_INFO".
 */
public class CollectionInfo {

    private Long id;
    /** Not-null value. */
    private String serviceTitle;
    /** Not-null value. */
    private String count;
    /** Not-null value. */
    private String evaluate;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String tag1;
    /** Not-null value. */
    private String tag2;

    public CollectionInfo() {
    }

    public CollectionInfo(Long id) {
        this.id = id;
    }

    public CollectionInfo(Long id, String serviceTitle, String count, String evaluate, String image, String tag1, String tag2) {
        this.id = id;
        this.serviceTitle = serviceTitle;
        this.count = count;
        this.evaluate = evaluate;
        this.image = image;
        this.tag1 = tag1;
        this.tag2 = tag2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getServiceTitle() {
        return serviceTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setServiceTitle(String serviceTitle) {
        this.serviceTitle = serviceTitle;
    }

    /** Not-null value. */
    public String getCount() {
        return count;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCount(String count) {
        this.count = count;
    }

    /** Not-null value. */
    public String getEvaluate() {
        return evaluate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getTag1() {
        return tag1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag1(String tag1) {
        this.tag1 = tag1;
    }

    /** Not-null value. */
    public String getTag2() {
        return tag2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag2(String tag2) {
        this.tag2 = tag2;
    }

}
