package com.qianfeng.android.myapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.qianfeng.android.myapp.dao.SearchHistory;
import com.qianfeng.android.myapp.dao.ShoppingCart;
import com.qianfeng.android.myapp.dao.CollectionInfo;

import com.qianfeng.android.myapp.dao.SearchHistoryDao;
import com.qianfeng.android.myapp.dao.ShoppingCartDao;
import com.qianfeng.android.myapp.dao.CollectionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig shoppingCartDaoConfig;
    private final DaoConfig collectionInfoDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final ShoppingCartDao shoppingCartDao;
    private final CollectionInfoDao collectionInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        shoppingCartDaoConfig = daoConfigMap.get(ShoppingCartDao.class).clone();
        shoppingCartDaoConfig.initIdentityScope(type);

        collectionInfoDaoConfig = daoConfigMap.get(CollectionInfoDao.class).clone();
        collectionInfoDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        shoppingCartDao = new ShoppingCartDao(shoppingCartDaoConfig, this);
        collectionInfoDao = new CollectionInfoDao(collectionInfoDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(ShoppingCart.class, shoppingCartDao);
        registerDao(CollectionInfo.class, collectionInfoDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.getIdentityScope().clear();
        shoppingCartDaoConfig.getIdentityScope().clear();
        collectionInfoDaoConfig.getIdentityScope().clear();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public ShoppingCartDao getShoppingCartDao() {
        return shoppingCartDao;
    }

    public CollectionInfoDao getCollectionInfoDao() {
        return collectionInfoDao;
    }

}
