package com.qianfeng.android.myapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_HISTORY".
 */
public class SearchHistory {

    private Long id;
    /** Not-null value. */
    private String content;

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String content) {
        this.id = id;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

}
